ugib/crud/urls.py
from django.urls import path

from . import views
from crud.views import UdsMetaHTMxTableView, UdsMetaAprHTMxTableView, HistoryView

app_name='crud'
urlpatterns = [
    path('', UdsMetaHTMxTableView.as_view(), name='table'),
    path('apr/', UdsMetaAprHTMxTableView.as_view(), name='table_apr'),
    path('profile/', views.profile, name='profile'),
    path('logout/', views.logout, name='logout'),
    path('profile/bascet/', views.bascet, name='bascet'),
    path('profile/history/', HistoryView.as_view(), name='history'),
    path('test/', views.test, name='test'),
    path('get_html_uds/', views.get_html_uds, name='get_html_uds'),
    path('get_html_apr/', views.get_html_apr, name='get_html_apr'),
    path('password_change/', views.password_change, name = "password_change"),
    path('refresh/', views.refresh_view, name = "refresh_view"),
    path('create/', views.create_post, name='create')
    # path('')
]

ugib/grr/urls.py
from django.urls import path

from . import views



app_name='grr'
urlpatterns = [
    # path('grr/', views.test , name='tttt'),
    path('grr-accom/', views.UdsMetaGrrAccomHTMxTableView.as_view(), name = "grr_accom"),
    path('grr-stage/', views.UdsMetaGrrStageHTMxTableView.as_view(), name = "grr_stage"),
    path('get_html_grr_stage/', views.get_html_grr_stage, name='get_html_grr'),
]

ugib/ugib/urls.py
from django.contrib import admin
from django.urls import path, include
from crud.views import UdsMetaHTMxTableView
urlpatterns = [
    path('', include("crud.urls")),
    path('', include("grr.urls")),
    path('admin/', admin.site.urls),
    path('__debug__/', include('debug_toolbar.urls')),
]
handler404 = 'crud.views.page_not_found'

ugib/grr/models.py
from django.db import models
from crud.models import UnlimitedCharField

def auto_incr_oid_grr_stage():#функция для осздания нового уникального oid
    largest = UdsMetaGrrStage.objects.all().order_by("oid").last()
    return largest.oid + 1

def auto_incr_oid_apr_accom():#функция для осздания нового уникального oid
    largest = UdsMetaGrrAccom.objects.all().order_by("oid").last()
    return largest.oid + 1

# Create your models here.
class UdsMetaGrrStage(models.Model):
    oid = models.BigIntegerField(default=auto_incr_oid_grr_stage, null = True, blank = True)
    uniq_id = UnlimitedCharField(primary_key = True)
    stor_folder = UnlimitedCharField( blank=True, null=True)
    stor_phys = UnlimitedCharField( blank=True, null=True)
    stor_reason = UnlimitedCharField( blank=True, null=True)
    stor_date = UnlimitedCharField( blank=True, null=True)
    stor_dept = UnlimitedCharField( blank=True, null=True)
    stor_person =UnlimitedCharField( blank=True, null=True)
    stor_desc = UnlimitedCharField( blank=True, null=True)
    stor_fmts = UnlimitedCharField( blank=True, null=True)
    stor_units = UnlimitedCharField( blank=True, null=True)
    obj_name = UnlimitedCharField( blank=True, null=True)
    type_of_work = UnlimitedCharField( blank=True, null=True)
    obj_synopsis = UnlimitedCharField( blank=True, null=True)#all null?
    obj_type = UnlimitedCharField( blank=True, null=True)
    obj_sub_type = UnlimitedCharField( blank=True, null=True)
    obj_assoc_inv_nums = UnlimitedCharField( blank=True, null=True)
    obj_date = UnlimitedCharField( blank=True, null=True)#all null?
    obj_year = UnlimitedCharField( blank=True, null=True)
    obj_authors = UnlimitedCharField(blank=True, null=True)
    obj_orgs = UnlimitedCharField( blank=True, null=True)
    obj_restrict = UnlimitedCharField( blank=True, null=True)#all null?
    obj_rights = UnlimitedCharField(blank=True, null=True)# тема повторятся дважды можно вынести в отдельный столбец
    obj_rdoc_name = UnlimitedCharField( blank=True, null=True)
    obj_rdoc_num = UnlimitedCharField( blank=True, null=True)
    obj_terms = UnlimitedCharField(blank=True, null=True)
    obj_sources = UnlimitedCharField( blank=True, null=True)#all null?
    obj_supl_info = UnlimitedCharField( blank=True, null=True)#all null?
    obj_main_min = UnlimitedCharField(blank=True, null=True)
    obj_supl_min = UnlimitedCharField( blank=True, null=True)
    obj_group_min = UnlimitedCharField( blank=True, null=True)
    obj_assoc_geol = UnlimitedCharField( blank=True, null=True)
    spat_atd_ate = UnlimitedCharField( blank=True, null=True)
    spat_loc = UnlimitedCharField(blank=True, null=True)
    spat_num_grid = UnlimitedCharField( blank=True, null=True)
    spat_coords_source = UnlimitedCharField(blank=True, null=True)
    spat_toponim = UnlimitedCharField(blank=True, null=True)
    inf_type = UnlimitedCharField( blank=True, null=True)
    inf_media = UnlimitedCharField(blank=True, null=True)
    path_others = UnlimitedCharField( blank=True, null=True)#all null 
    obj_main_group = UnlimitedCharField( blank=True, null=True)
    obj_sub_group = UnlimitedCharField( blank=True, null=True)
    path_local = UnlimitedCharField( blank=True, null=True)
    path_cloud =UnlimitedCharField( blank=True, null=True)
    status = UnlimitedCharField( blank=True, null=True)#all null
    timecode = UnlimitedCharField( blank=True, null=True)#all null
    
    
    class Meta:
        managed = False
        db_table = 'uds_meta_grr_stage'
    


class UdsMetaGrrAccom(models.Model):
    oid = models.BigIntegerField(default=auto_incr_oid_apr_accom, null = True, blank = True)
    uniq_id = UnlimitedCharField(primary_key = True)
    stor_folder = UnlimitedCharField(blank=True, null=True)
    stor_phys = UnlimitedCharField(blank=True, null=True)
    stor_reason = UnlimitedCharField( blank=True, null=True)
    stor_date = UnlimitedCharField( blank=True, null=True)
    stor_dept = UnlimitedCharField( blank=True, null=True)
    stor_person =UnlimitedCharField( blank=True, null=True)
    stor_desc = UnlimitedCharField( blank=True, null=True)
    stor_fmts = UnlimitedCharField( blank=True, null=True)
    stor_units = UnlimitedCharField( blank=True, null=True)
    obj_name = UnlimitedCharField( blank=True, null=True)
    type_of_work = UnlimitedCharField( blank=True, null=True)
    obj_synopsis = UnlimitedCharField( blank=True, null=True)#all null?
    obj_type = UnlimitedCharField( blank=True, null=True)
    obj_sub_type = UnlimitedCharField( blank=True, null=True)
    obj_assoc_inv_nums = UnlimitedCharField( blank=True, null=True)
    obj_date = UnlimitedCharField( blank=True, null=True)#all null?
    obj_year = UnlimitedCharField( blank=True, null=True)
    obj_authors = UnlimitedCharField(blank=True, null=True)
    obj_orgs = UnlimitedCharField( blank=True, null=True)
    obj_restrict = UnlimitedCharField( blank=True, null=True)#all null?
    obj_rights = UnlimitedCharField(blank=True, null=True)# тема повторятся дважды можно вынести в отдельный столбец
    obj_rdoc_name = UnlimitedCharField( blank=True, null=True)
    obj_rdoc_num = UnlimitedCharField( blank=True, null=True)
    obj_terms = UnlimitedCharField(blank=True, null=True)
    obj_sources = UnlimitedCharField( blank=True, null=True)#all null?
    obj_supl_info = UnlimitedCharField( blank=True, null=True)#all null?
    obj_main_min = UnlimitedCharField(blank=True, null=True)
    obj_supl_min = UnlimitedCharField( blank=True, null=True)
    obj_group_min = UnlimitedCharField( blank=True, null=True)
    obj_assoc_geol = UnlimitedCharField( blank=True, null=True)
    spat_atd_ate = UnlimitedCharField( blank=True, null=True)
    spat_loc = UnlimitedCharField(blank=True, null=True)
    spat_num_grid = UnlimitedCharField( blank=True, null=True)
    spat_coords_source = UnlimitedCharField(blank=True, null=True)
    spat_toponim = UnlimitedCharField(blank=True, null=True)
    inf_type = UnlimitedCharField( blank=True, null=True)
    inf_media = UnlimitedCharField(blank=True, null=True)
    path_others = UnlimitedCharField( blank=True, null=True)#all null 
    obj_main_group = UnlimitedCharField( blank=True, null=True)
    obj_sub_group = UnlimitedCharField( blank=True, null=True)
    path_local = UnlimitedCharField( blank=True, null=True)
    path_cloud =UnlimitedCharField( blank=True, null=True)
    status = UnlimitedCharField( blank=True, null=True)#all null
    timecode = UnlimitedCharField( blank=True, null=True)#all null


    class Meta:
        managed = False
        db_table = 'uds_meta_grr_accom'
        
class UdsMetaProtocols(models.Model):
    oid = models.BigIntegerField(default=auto_incr_oid_apr_accom, null = True, blank = True)
    uniq_id = UnlimitedCharField(primary_key = True)
    stor_folder = UnlimitedCharField( blank=True, null=True)
    stor_phys = UnlimitedCharField( blank=True, null=True)
    stor_reason = UnlimitedCharField( blank=True, null=True)
    stor_date = UnlimitedCharField(blank=True, null=True)
    stor_dept = UnlimitedCharField(blank=True, null=True)
    stor_person = UnlimitedCharField(blank=True, null=True)
    stor_desc = UnlimitedCharField( blank=True, null=True)
    stor_fmts = UnlimitedCharField( blank=True, null=True)
    stor_units = UnlimitedCharField( blank=True, null=True)
    obj_name = UnlimitedCharField(blank=True, null=True)
    type_of_work = UnlimitedCharField( blank=True, null=True)
    obj_synopsis = UnlimitedCharField(blank=True, null=True)
    obj_type = UnlimitedCharField(blank=True, null=True)
    obj_sub_type = UnlimitedCharField(blank=True, null=True)
    obj_assoc_inv_nums = UnlimitedCharField(blank=True, null=True)
    obj_date = UnlimitedCharField( blank=True, null=True)
    obj_year = UnlimitedCharField( blank=True, null=True)
    obj_authors = UnlimitedCharField( blank=True, null=True)
    obj_orgs = UnlimitedCharField(blank=True, null=True)
    obj_restrict = UnlimitedCharField(blank=True, null=True)
    obj_rights = UnlimitedCharField( blank=True, null=True)
    obj_rdoc_name = UnlimitedCharField(blank=True, null=True)
    obj_rdoc_num = UnlimitedCharField(blank=True, null=True)
    obj_terms = UnlimitedCharField(blank=True, null=True)
    obj_sources = UnlimitedCharField(blank=True, null=True)
    obj_supl_info = UnlimitedCharField( blank=True, null=True)
    obj_main_min = UnlimitedCharField(blank=True, null=True)
    obj_supl_min = UnlimitedCharField( blank=True, null=True)
    obj_group_min = UnlimitedCharField(blank=True, null=True)
    obj_assoc_geol = UnlimitedCharField( blank=True, null=True)
    spat_atd_ate = UnlimitedCharField( blank=True, null=True)
    spat_loc = UnlimitedCharField( blank=True, null=True)
    spat_num_grid = UnlimitedCharField( blank=True, null=True)
    spat_coords_source = UnlimitedCharField(blank=True, null=True)
    spat_toponim = UnlimitedCharField( blank=True, null=True)
    inf_type = UnlimitedCharField( blank=True, null=True)
    inf_media = UnlimitedCharField( blank=True, null=True)
    path_others = UnlimitedCharField( blank=True, null=True)
    obj_main_group = UnlimitedCharField( blank=True, null=True)
    obj_sub_group = UnlimitedCharField( blank=True, null=True)
    path_local = UnlimitedCharField( blank=True, null=True)
    path_cloud = UnlimitedCharField( blank=True, null=True)
    status = UnlimitedCharField( blank=True, null=True)
    timecode = UnlimitedCharField( blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'uds_meta_protocols'

ugib/grr/views.py
from datetime import datetime
from pprint import pprint
import csv
import re
import glob
import os
import io

import xlsxwriter
from docxtpl import DocxTemplate
from xlsxwriter.workbook import Workbook
from django.shortcuts import render, redirect
from django.core.exceptions import ObjectDoesNotExist
from django.db.utils import IntegrityError
from django.http import HttpResponse, FileResponse
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout as django_logout
from django.contrib.auth.models import User, Group
from django.db.models import Q
from django_tables2 import SingleTableMixin
from django_filters.views import FilterView
from django.contrib.auth.hashers import PBKDF2PasswordHasher


from crud.views import create_uniq_id, UdsMetaHTMxTableView
from crud.models import History, UdsMeta, Bascet, Order, UserInfo
from .models import UdsMetaGrrStage, UdsMetaGrrAccom
from crud.HelperUdsMeta import HelperUdsMet, HelperUdsMetApr
from crud.forms import LoginForm, UdsMetaForm, WordDocFilling, RegisterForm, MyChangePassword
from crud.history import decor
from .tables import UdsMetaGrrAccomTable, UdsMetaGrrStageTable
from .filters import  UdsMetaGrrStageFilter, UdsMetaGrrAccomFilter



class UdsMetaGrrStageHTMxTableView(UdsMetaHTMxTableView, SingleTableMixin, FilterView): # представление для базовой страницы
    table_class = UdsMetaGrrStageTable
    data_models = UdsMetaGrrStage
    redirect_url = "/grr-stage/"
    filterset_class = UdsMetaGrrStageFilter
    paginate_by = 25
    login_form = LoginForm()
    register_form =  RegisterForm()
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # stor_phys_dict = {} 
        # buff = UdsMetaGrrStage.objects.order_by("-oid")
        # for i in buff:
        #     stor_phys_dict.update({i.status: stor_phys_dict.get(i.status, 0) + 1})
        # context["stor_phys_p"] = dict(sorted(stor_phys_dict.items(), reverse=True,key=lambda item: item[1]))        
        # pprint(context["stor_phys_p"])
        
        context["choise"] = "grr_stage"
        return context

    
    def get_template_names(self): 
        if self.request.htmx:
            template_name = "grr/index/grr_stage/index_table_grr_stage_partial.html"
        else:
            template_name = "grr/index/grr_stage/index_table_grr_stage_htmx.html"
        return template_name


def get_html_grr_stage(request):
    context = {}
    context["user"] = request.user
    context["current_date"] =  datetime.strftime(datetime.now(), "%d.%m.%Y")
    iniz = request.user.first_name.split(" ")
    iniz = iniz[0][0] + "." + iniz[1][0] + "."#Создание инициалов из Имени и Отчества
    context["iniz"] = iniz
    context["userInfo"] = UserInfo.objects.get(user_id = request.user.id)
    # buff2 = UdsMeta.objects.filter(obj_sub_group = "02RFGF").order_by("-oid").first()
    print(request.GET)
    if 'oid' in request.GET:
        context["record"] = UdsMetaGrrStage.objects.get(oid = request.GET["oid"])
        return render(request, 'crud/form/update_apr.html', context=context)
    if 'oid_accom' in request.GET:
        context["record"] = UdsMetaGrrAccom.objects.get(oid = request.GET["oid_accom"])
        return render(request, 'crud/form/update_apr.html', context=context)
    if "GRR-STAGE" == request.GET["choise"]:
        context["choise"] = "grr-stage"
        context["uniq_id"] = create_uniq_id(choise=context["choise"],current_date = context["current_date"] )
        return render(request, "grr/form/grr_stage.html", context=context)
    if "GRR-ACCOM" == request.GET["choise"]:
        context["choise"] = "grr-accom"
        context["uniq_id"] = create_uniq_id(choise=context["choise"],current_date = context["current_date"] )
        return render(request, "grr/form/grr_accom.html", context=context)
    
    

class UdsMetaGrrAccomHTMxTableView(UdsMetaHTMxTableView,SingleTableMixin, FilterView): # представление для базовой страницы
    table_class = UdsMetaGrrAccomTable
    data_models = UdsMetaGrrAccom
    redirect_url = "/grr-accom/"
    
    filterset_class = UdsMetaGrrAccomFilter
    paginate_by = 25
    login_form = LoginForm()
    register_form =  RegisterForm()
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        stor_phys_dict = {} 
        # buff = UdsMeta.objects.order_by("-oid")
        # for i in buff:
        #     stor_phys_dict.update({i.stor_folder: stor_phys_dict.get(i.stor_folder, 0) + 1})
        # context["stor_phys_p"] = dict(sorted(stor_phys_dict.items(), reverse=True,key=lambda item: item[1]))        
        # pprint(context["stor_phys_p"])
        context["choise"] = "grr_accom"
        
        return context

    
    def get_template_names(self): 
        if self.request.htmx:
            template_name = "grr/index/grr_accom/index_table_grr_accom_partial.html"
        else:
            template_name = "grr/index/grr_accom/index_table_grr_accom_htmx.html"
        return template_name

ugib/grr/templates/grr/index/grr_accom/index_table_grr_accom_htmx.html
{% extends "crud/base.html" %}

{% load render_table from django_tables2 %}
{% load i18n %}
{% load crispy_forms_tags %}
{% load static %}
{%block script%}
<link rel="stylesheet" href="{% static 'css/main_grr_accom.css' %}">
<link rel="stylesheet" href="{% static 'css/validation.css' %}">
<script src="{% static 'js/main_grr_accom.js' %}"></script>  
<script src="{% static 'js/validators_grr_accom.js' %}"></script>  
<script src="{% static 'js/jquery.js' %}"></script>  

{%endblock%}
{%block title%}
    {{choise}}
{%endblock%}
{% block body %}
    <div class = "boss_div">
      <div class = "link_div">
        <button type="button" class="btn btn-link" onclick="window.location.href = '/';" >01FOUND</button>
        <button type="button" class="btn btn-link" onclick="window.location.href = '/apr/'">APR</button>
        <button type="button" class="btn btn-link" onclick="window.location.href = '/grr-stage/'">GRR-STAGE</button>
        <button type="button" class="btn btn-link my" onclick="window.location.href ='/grr-accom/'" id = "grr_accom_btn">GRR-ACCOM</button>
      </div>
    <div class = "head">
      {% if user.is_active %}
      {% if common_user %}   
        <a href = "{% url "crud:profile"%}">Профиль</a>
      {% endif %} 
        <a href = "{% url "crud:logout"%}"> Выйти</a>
        {% if super_users %}
        <button type="button" class="btn btn-link" onclick="refresh_meta(event)">Обновить</button>
        <a href = "{% url "crud:history"%}"> История</a>
        {% endif %}

        <br>
      {% endif %}
        
    {# Search form #}
    {% if user.is_active %}
    <form hx-get="/grr-accom/" 
          hx-target="div.table-container" 
          hx-swap="outerHTML" 
          hx-indicator=".progress" 
          class="form-inline">
        {% crispy filter.form %}
    </form>
    {% endif %}
</div>
<div class = "modal_form">
    {% if user.is_active == False %} 
    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModalCenter" onClick= "change_style(event)">
        Войти
    </button>
    <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true" data-keyboard="false" data-backdrop="static">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content create_content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Вход</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick= "unchange_style(event)">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body">
              <div class="form-group">
              <form  method = "POST">
                  {% csrf_token %}
                  {{form|crispy}}
                  <button type = "submit" name = "login" onclick= "unchange_style(event)"> Войти</button>
                </form>
                <a href = "{% url "crud:password_change"%}"> Восстановить пароль</a>

              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick= "unchange_style(event)" >Close</button>
          </div>
        </div>
      </div>
    </div>
</div> 

<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#RegModalCenter"  onClick= "change_style(event)">
  Зарегистрироваться 
</button>

<div class="modal fade" id="RegModalCenter" tabindex="-1" role="dialog" aria-labelledby="RegModalCenterTitle" aria-hidden="true" data-keyboard="false" data-backdrop="static">
<div class="modal-dialog modal-dialog-centered" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLongTitle">Вход</h5>
      <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick= "unchange_style(event)">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    <div class="modal-body">
        <div class="form-group">
        <form  method = "POST">
            {% csrf_token %}
            {{register_form|crispy}}
            <button type = "submit" name = "register" onclick= "unchange_style(event)"> Зарегистрироваться </input>
          </form>
        </div>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-dismiss="modal" onclick= "unchange_style(event)">Close</button>
    </div>
  </div>
</div>
</div>
</div> 
    {% endif %}

<div class = "create_div">
{% if user.is_active%}
{% if common_user == False %}
<form method = "POST">
  {% csrf_token %}
<button type = 'submit'  class="btn btn-primary"  value = "{{record.oid}}" name = "export_exel"> Экспорт Exel </button>
</form>
<form method = "POST">
	{% csrf_token %}
	<button type = 'submit'  class="btn btn-primary" value = "" name = "export_exel_partially" onClick = "some_attrs_export()"> Экспорт Exel(частично) </button>
</form>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#ModalLong" id = "create_button"  onClick= "change_style(event)">
    Создать
</button>
{% endif %}
</div>
{% endif %}
<div class="modal fade" id="ModalLong" tabindex="-1" role="dialog" aria-labelledby="ModalLongTitle" aria-hidden="true" data-keyboard="false" data-backdrop="static">
    <div class="modal-dialog modal-dialog-centered modal-xl modal-custom " id = "custom_modal" role="document">
      <div class="modal-content modal-content-custom" >
        <div class="modal-header">
          <select>
            <option>GRR-ACCOM</option>
          </select>
          <select id = "select_sub" onClick = "dinamic_form(event)" >
            <option>GRR-ACCOM</option>
          </select>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close" onclick= "unchange_style(event)">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
            <form  method = "POST" id = "create_form">
                {% csrf_token %}
                <div class = "col">
                  <div class = "col" id = "valid_div">
        
				          </div>
                </div>
                <button type="button" id = "my_but" class="btn btn-secondary my_but" data-dismiss="modal"  onClick = "createPost(event)"  form = "{{record.oid}}"> Создать </button>
              </form>
        </div>
        <div class="modal-footer">
          <button type="button"  class="btn btn-secondary" data-dismiss="modal" onclick= "unchange_style(event)">Close</button>
        </div>
      </div>

    </div>
  </div>

</div>

</div>
<div class="modal fade" id="updModal" tabindex="-1" role="dialog" aria-labelledby="updModalTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <textarea class = "modal_area" id = "modal_area">  </textarea>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal"  id = "close_btn">Close</button>
        <button type="button" class="btn btn-primary" data-dismiss="modal" onClick = "upd_post(event)" id = "upd_btn">Изменить</button>
      </div>
    </div>
  </div>
</div>
    {# Progress indicator #}
    <div class="progress">
        <div class="indeterminate"></div>
    </div>

    {# The actual table #}
    <div class = "obs_table">
      <input hidden value = '{{common_user}}'  id = 'info_user'>
    {% render_table table %}
	</div>
{% endblock %}

ugib/grr/templates/grr/index/grr_accom/index_table_grr_accom_partial.html
{% load render_table from django_tables2 %}
{% load static %}
{%block script%}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://unpkg.com/htmx.org@1.8.0" integrity="sha384-cZuAZ+ZbwkNRnrKi05G/fjBX+azI9DNOkNYysZ0I/X5ZFgsmMiBXgDZof30F5ofc" crossorigin="anonymous"></script>
<script
  src="https://code.jquery.com/jquery-3.3.1.js"
  integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60="
  crossorigin="anonymous"></script>
<link rel="stylesheet" href="{% static 'css/main_grr_accom.css' %}">
<script src="{% static 'js/main_grr_accom.js' %}"></script>  
{%endblock%}
{% render_table table %}